try{
    console.log('hello')
}catch(err){
    console.log(err)
}

console.log('hello Outside')